"use strict";

var _navbar = require("../util/navbar");

require("../css/style.scss");

require("bootstrap");

var nav = (0, _navbar.creatNav)();
document.getElementById("nav-capitulo2").appendChild(nav);
var article = document.createElement("article");
var container = document.createElement("div");
container.classList = "container";
article.appendChild(container);
var row = document.createElement("div");
row.classList = "row";
container.appendChild(row);
var grid = document.createElement("div");
grid.classList = "col-lg-8 col-md-10 mx-auto";
row.appendChild(grid);
var title1 = document.createElement("h2");
title1.classList = "section-heading";
title1.innerText = "Parte 1";
grid.appendChild(title1);
var parrafo1 = document.createElement("p");
parrafo1.innerText = "Unos d\xEDas antes\u2026";
grid.appendChild(parrafo1);
var parrafo2 = document.createElement("p");
parrafo2.innerText = "Carlos, se acerca el cumplea\xF1os de Antonio, \xBFque se te ocurre que le podemos hacer? \xBFSer\xE1 que le compramos la computadora que tanto nos ha pedido? \xC9l me respondi\xF3 que Antonio preferir\xEDa una fiesta con sus amigos que una computadora. Yo sab\xEDa de que eso no era cierto, pero decid\xED seguirle la corriente porque no quer\xEDa comprar una computadora tan cara. Carlos me dijo que ten\xEDa una buena idea, la cual ten\xEDa que ver con una gran fiesta sorpresa con la familia y sus compa\xF1eros de clase. Me dijo que no me preocupara, que esta vez \xE9l se encargar\xEDa de todo.";
grid.appendChild(parrafo2);
var parrafo3 = document.createElement("p");
parrafo3.innerText = "Yo he sido siempre la que ha organizado las fiestas de cumplea\xF1os de mis hijos. Me preocupaba que Carlos no pudiera, pero bueno al final decid\xED dejarlo y apoyarlo. Me dijo que su idea era armar la fiesta como siempre en la casa de mi hermana. Me pidi\xF3 ayuda con las invitaciones y con pedirle permiso a mi hermana de usar su casa. Le pregunt\xE9 mas detalles, pero no me quiso decir nada. \xA1Agu\xE1ntenselo!, me dijo que, si me dec\xEDa los detalles, lo iba a empezar a contradecir, criticar, y que no lo iba a dejar en paz. Qu\xE9 se cree ese hombre, pero bueno\u2026 no quiero empezar a discutir, as\xED que me conformar\xE9.";
grid.appendChild(parrafo3);
var img1 = document.createElement("a");
img1.href = "../img/enojada.gif";
img1.innerHTML = "<img class=\"img-fluid centrar\" src=\"img/enojada.gif\" alt=\"\">";
grid.appendChild(img1);
var title2 = document.createElement("h2");
title2.classList = "section-heading";
title2.innerText = "Parte 2";
grid.appendChild(title2);
var parrafo4 = document.createElement("p");
parrafo4.innerText = "\xA1Es el d\xEDa!, lev\xE1ntate Carlos. Hay que levantar a los ni\xF1os para ir a decirle feliz cumplea\xF1os a Antonio. Me levant\xE9 r\xE1pido y baj\xE9 a hacer loncheras, mientras Carlos ni en cuenta. Quisiera tener ese don de poder quedarme dormida tan r\xE1pido y profundo como \xE9l, pero bueno. Al rato lleg\xF3 con Daniel y Luis y me dijeron que ya estaban listos, as\xED que fuimos, lo despertamos (aunque creo que ya estaba despierto) y lo abrazamos. Luego me desped\xED y me fui a trabajar.";
grid.appendChild(parrafo4);
var parrafo5 = document.createElement("p");
parrafo5.innerText = "En la noche regres\xE9 a la casa y mientras Antonio estaba en su cuarto haciendo tareas, le pregunt\xE9 a Carlos si todo estaba listo, a lo cu\xE1l me respondi\xF3 que por supuesto. As\xED que cuando estuvimos listos y recibimos el mensaje de mi hermana, nos dirigimos a su casa. Al llegar entramos y yo empec\xE9 a gritar feliz cumplea\xF1os, pero mi grito fue interrumpido por el vac\xEDo del lugar. Admito que la decoraci\xF3n me gust\xF3 mucho, \xBFpero y la gente? Carlos me dijo que supuestamente deber\xEDan de haber estado afuera todos y nada m\xE1s entrando ellos deb\xEDan aparecer. Me dijo que llamara a mi hermana, pues ella estaba con los invitados. La llam\xE9, pero no contest\xF3. Al cabo de una media hora, mi paciencia colm\xF3 y le fui a reclamar a Carlos y le dije que de ahora en adelante yo me encargar\xEDa de los cumplea\xF1os y no \xE9l.";
grid.appendChild(parrafo5);
var img2 = document.createElement("a");
img2.href = "../img/gritando.gif";
img2.innerHTML = "<img class=\"img-fluid centrar\" src=\"img/gritando.gif\" alt=\"\">";
grid.appendChild(img2);
var linea1 = document.createElement("hr");
grid.appendChild(linea1);
var btn = document.createElement("div");
btn.classList = "clearfix";
btn.innerHTML = "<a class=\"btn btn-primary float-right\" href=\"capitulo3.html\">Capitulo 3 &rarr;</a>";
grid.appendChild(btn);
document.getElementById("capitulo2-text").appendChild(article);