"use strict";

var _navbar = require("../util/navbar");

require("../css/style.scss");

require("bootstrap");

var nav = (0, _navbar.creatNav)();
document.getElementById("nav-capitulo1").appendChild(nav);
var article = document.createElement("article");
var container = document.createElement("div");
container.classList = "container";
article.appendChild(container);
var row = document.createElement("div");
row.classList = "row";
container.appendChild(row);
var grid = document.createElement("div");
grid.classList = "col-lg-8 col-md-10 mx-auto";
row.appendChild(grid);
var title1 = document.createElement("h2");
title1.classList = "section-heading";
title1.innerText = "Parte 1";
grid.appendChild(title1);
var parrafo1 = document.createElement("p");
parrafo1.innerText = "Al fin, hoy es el d\xEDa; despu\xE9s de esperar un a\xF1o, es mi cumplea\xF1os. \xBFQu\xE9 me tendr\xE1n preparado mis pap\xE1s\u2026? \xBFMe ir\xE1n a hacer una fiesta sorpresa\u2026 o tal vez me van a dar la computadora que durante tanto tiempo he deseado? \xA1Que emoci\xF3n!, no puedo esperar a ver que me depara el futuro\u2026";
grid.appendChild(parrafo1);
var parrafo2 = document.createElement("p");
parrafo2.innerText = "De repente, mis pensamientos fueron interrumpidos por unos pasos que se acercaban a mi habitaci\xF3n. Mis pap\xE1s, junto con mis hermanos entraron sigilosamente y gritaron\u2026 \xA1feliz cumplea\xF1os Antonio!, se lanzaron a darme un gran abrazo. Yo, muy emocionado, les di las gracias y tambi\xE9n los abrac\xE9. Me dijeron que me fuera a ba\xF1ar y que me alistara para ir al colegio, lo cual hice, y que luego bajara a desayunar. \xA1El desayuno estaba delicioso! Una torre de panqueques, y un Milkshake de banano, mi favorito; el d\xEDa hab\xEDa empezado estupendo.";
grid.appendChild(parrafo2);
var parrafo3 = document.createElement("p");
parrafo3.innerText = "Al llegar al colegio, todos mis compa\xF1eros me dijeron feliz cumplea\xF1os. Sin embargo, muchos de ellos andaban algo sospechosos, como si evitaran que me enterara de algo, \xBFmi fiesta sorpresa de cumplea\xF1os tal vez? No pod\xEDa aguantar la curiosidad, as\xED que en el recreo me acerqu\xE9 sigilosamente a mis amigos, los cuales estaban hablando en voz baja. Lo \xFAnico que logre escuchar fueron estas palabras: sorpresa\u2026 noche\u2026 fiesta\u2026, definitivamente hablaban de una fiesta sorpresa\u2026 \xA1mi fiesta sorpresa! El resto del d\xEDa, no pude pensar en nada m\xE1s que en las posibilidades de mi fiesta. \xA1Que emoci\xF3n!";
grid.appendChild(parrafo3);
var img1 = document.createElement("a");
img1.href = "../img/feliz.gif";
img1.innerHTML = "<img class=\"img-fluid centrar\" src=\"img/feliz.gif\" alt=\"\">";
grid.appendChild(img1);
var title2 = document.createElement("h2");
title2.classList = "section-heading";
title2.innerText = "Parte 2";
grid.appendChild(title2);
var parrafo4 = document.createElement("p");
parrafo4.innerText = "En la tarde noche, ya en mi casa, mis pap\xE1s me dijeron que ten\xEDamos que salir. Por supuesto, yo ya sab\xEDa a que iba todo esto. Me arregl\xE9, me puse guapo y nos fuimos. Al final, llegamos a la casa de mi t\xEDa Luc\xEDa, una casa muy grande donde normalmente celebr\xE1bamos los cumplea\xF1os. Nos bajamos del carro y mis pap\xE1s notaron mi emoci\xF3n, pero no dijeron nada. Cuando llegamos a la puerta del gran sal\xF3n, mis pap\xE1s la abrieron y dijeron: \xA1Feliz cumplea\u2026.! No hab\xEDa nadie. Todo el lugar estaba arreglado, pero no hab\xEDa nadie. Al principio, estaba emocionado esperando que de alg\xFAn lado salieran los invitados con muchos regalos, pero\u2026 nadie. Me puse nervioso y triste, en especial al ver que mis pap\xE1s estaban nerviosos y mi mam\xE1 le gritaba a mi pap\xE1. \xBFQu\xE9 estaba pasando\u2026, me abandonaron, o acaso nadie quiso venir? No pude evitarlo y me puse a llorar.";
grid.appendChild(parrafo4);
var img2 = document.createElement("a");
img2.href = "../img/triste.gif";
img2.innerHTML = "<img class=\"img-fluid centrar\" src=\"img/triste.gif\" alt=\"\">";
grid.appendChild(img2);
var linea1 = document.createElement("hr");
grid.appendChild(linea1);
var btn = document.createElement("div");
btn.classList = "clearfix";
btn.innerHTML = "<a class=\"btn btn-primary float-right\" href=\"capitulo2.html\">Capitulo 2 &rarr;</a>";
grid.appendChild(btn);
document.getElementById("capitulo1-text").appendChild(article);